name: bfx-interview
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.8
  - biopython>=1.81
  - numpy>=1.24.0
  - pyyaml>=6.0
  - mafft>=7.520
  - flye
  - tqdm
  - seqkit
  - samtools
  - minimap2
  - pip:
    - matplotlib
    - seaborn
    - edlib
